language: python
python:
- '3.10'
dist: bionic
os: linux
arch:
  - arm64
jobs:
  fast_finish: true

install:
 - pip install maturin

script:
 - maturin build

deploy:
  provider: script
  script: bash .ci/deploy_to_pypi.sh
  on:
    branch: master
    python: "3.10"
    repo: ImperatorLang/pyaiken
