language: python
python:
- '3.10'
dist: bionic
os: linux
arch:
  - arm64
jobs:
  fast_finish: true

install:
 - echo "skipped"

script:
 - echo "skipped"

deploy:
  provider: script
  script: ".ci/deploy_to_pypi.sh"
  on:
    python: "3.10"
    tags: true
    repo: ImperatorLang/pyaiken