language:
 - python
 - rust
python:
- '3.8'
- '3.9'
- '3.10'
dist: bionic
os: linux
arch: arm64
jobs:
  fast_finish: true

install:
 # install latest version of rust
 - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
 - pip install maturin

script:
 - maturin build

deploy:
  provider: script
  script: bash .ci/deploy_to_pypi.sh
  on:
    branch: master
    python: "3.10"
    repo: ImperatorLang/pyaiken
